### ISSUE TITLE
Please show how to do code syntax highlight

### ISSUE THREAD

**Issue by noamtamim** [webpro/github-pages-example#1]
I tried adding a source snippet. It looks great in the code view, but not on GH pages:

Source: https://github.com/noamtamim/github-pages-example/blob/gh-pages/index.md
Page: https://noamtamim.github.io/github-pages-example/index.html

I think the missing piece is a css file that includes styles for the highlight classes, but I don't have an example showing it.

**Comment by webpro** [comment]
Hi @noamtamim, I'm seeing syntax-highlighted content. This looks OK to me now?

**Comment by noamtamim** [comment]
Yes, I copied some code rough demo page. But it's not a real solution; I'd like to see a proper example. Only if you happen to have the time, of course.
Thanks!

**Comment by webpro** [comment]
My example repo has nothing to do with syntax highlighting, so I'm not sure about your question?

**Comment by noamtamim** [comment]
I understand; however I got to your post on Medium looking for a solution, and syntax highlighting was the only missing piece (for my case). Thought you example may be more complete with it.

Anyway, I figured it out now. Thanks!
